/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Edge;
import model.Graph;
import model.Graphml;
import model.Node;

/**
 *
 * @author Juliana
 */
public class frmCaminho extends javax.swing.JFrame {

    Graph graph = new Graph();
    frmInterface frmI;
    String o = "", d = "";

    /**
     * Creates new form frmEditarNode
     */
    public frmCaminho() {
        centralizarComponente();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        cbVerificaOrigem = new javax.swing.JComboBox<>();
        cbVerificaDestino = new javax.swing.JComboBox<>();
        lblNo1 = new javax.swing.JLabel();
        btnConfirmarVertice = new javax.swing.JButton();
        btnCancelarVertice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Verificar Caminho");

        lblNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNo.setText("Origem");

        lblNo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNo1.setText("Destino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVerificaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVerificaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNo1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNo)
                    .addComponent(lblNo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVerificaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVerificaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfirmarVertice.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirmarVertice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnConfirmarVertice.setText("Confirmar");
        btnConfirmarVertice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnConfirmarVertice.setContentAreaFilled(false);
        btnConfirmarVertice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarVertice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmarVerticeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmarVerticeMouseExited(evt);
            }
        });
        btnConfirmarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVerticeActionPerformed(evt);
            }
        });

        btnCancelarVertice.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarVertice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelarVertice.setText("Cancelar");
        btnCancelarVertice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancelarVertice.setContentAreaFilled(false);
        btnCancelarVertice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarVertice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarVerticeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarVerticeMouseExited(evt);
            }
        });
        btnCancelarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVerticeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarVerticeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarVerticeMouseEntered
        btnConfirmarVertice.setContentAreaFilled(true);
        btnConfirmarVertice.setBackground(Color.gray);
    }//GEN-LAST:event_btnConfirmarVerticeMouseEntered

    private void btnConfirmarVerticeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarVerticeMouseExited
        btnConfirmarVertice.setContentAreaFilled(false);
    }//GEN-LAST:event_btnConfirmarVerticeMouseExited

    private void btnConfirmarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVerticeActionPerformed
        List<Node> a = new ArrayList<Node>();
        try {
            if (frmI == null) {
                frmI = new frmInterface();
                frmI.setVisible(true);

                frmI.getCadeiaOuCaminho(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault(), "Caminho: " + graph.verificaCadeia((String) cbVerificaOrigem.getSelectedItem(), (String) cbVerificaDestino.getSelectedItem(), 0, a));
            } else {
                frmI.setVisible(true);
                frmI.setState(frmInterface.NORMAL);
                frmI.getCadeiaOuCaminho(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault(), "Caminho: " + graph.verificaCadeia((String) cbVerificaOrigem.getSelectedItem(), (String) cbVerificaDestino.getSelectedItem(), 0, a));
            }
            this.dispose();
        } catch (Exception e) {
            if (frmI == null) {
                frmI = new frmInterface();
                frmI.setVisible(true);

                frmI.getCadeiaOuCaminho(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault(), "Caminho: não existe");
            } else {
                frmI.setVisible(true);
                frmI.setState(frmInterface.NORMAL);
                frmI.getCadeiaOuCaminho(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault(), "Caminho: não existe");
            }
            this.dispose();
        }

//        cbVerificaOrigem.removeAllItems();
    }//GEN-LAST:event_btnConfirmarVerticeActionPerformed

    private void btnCancelarVerticeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarVerticeMouseEntered
        btnCancelarVertice.setContentAreaFilled(true);
        btnCancelarVertice.setBackground(Color.gray);
    }//GEN-LAST:event_btnCancelarVerticeMouseEntered

    private void btnCancelarVerticeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarVerticeMouseExited
        btnCancelarVertice.setContentAreaFilled(false);
    }//GEN-LAST:event_btnCancelarVerticeMouseExited

    private void btnCancelarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVerticeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarVerticeActionPerformed
    public void setAlteracao(List<Node> node, List<Edge> edge, String nome, String tipo) {

        graph.setNodes(node);
        graph.setEdges(edge);
        graph.setId(nome);
        graph.setEdgedefault(tipo);

        for (int i = 0; i < graph.getNodes().size(); i++) { //Adiciona os vertices no combobox    
            cbVerificaOrigem.addItem(graph.getNodes().get(i).getId());
            cbVerificaDestino.addItem(graph.getNodes().get(i).getId());
        }
    }

    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 4, (ds.height - dw.height) / 4);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCaminho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCaminho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCaminho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCaminho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCaminho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarVertice;
    private javax.swing.JButton btnConfirmarVertice;
    private javax.swing.JComboBox<String> cbVerificaDestino;
    private javax.swing.JComboBox<String> cbVerificaOrigem;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblNo1;
    // End of variables declaration//GEN-END:variables
}
