package view;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Edge;
import model.Graph;
import model.Graphml;
import model.Node;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Luiz Fernando
 */
public class frmInterface extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Graph graph = new Graph();
    Graphml graphml = new Graphml();
    private String choose = null;
    List<Node> listaNode = new ArrayList<Node>();
    List<Edge> listaEdge = new ArrayList<Edge>();
    List<Edge> listaRec = new ArrayList<Edge>();
    frmEditarNode edn;
    frmEditarAresta ede;
    frmCadeia vcad;
    frmCaminho vcam;
    int w = 0;
    int h = 0;
    int m;

    public frmInterface() {
//        centralizarComponente();
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        iconNovo = new javax.swing.JLabel();
        iconAbrir = new javax.swing.JLabel();
        iconSalvar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnMatrizAdj = new javax.swing.JButton();
        btnMatrizInc = new javax.swing.JButton();
        btnListaAdj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnAdicionarVertice = new javax.swing.JButton();
        txtaddVertice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAlterarVertice = new javax.swing.JButton();
        btnDeletarVertice = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnAdicionarAresta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbDestino = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtNomeAresta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btndeletarAresta = new javax.swing.JButton();
        btnAlterarAresta = new javax.swing.JButton();
        txtPesoAresta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbOrigem = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        lblNomeGrafo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTipoGrafo = new javax.swing.JLabel();
        btnLimpaVA = new javax.swing.JButton();
        btnLimpaAresta = new javax.swing.JButton();
        btnMostrarVA = new javax.swing.JButton();
        btnGerarGrafico = new javax.swing.JButton();
        lblGrafico = new javax.swing.JLabel();
        imgGrafico = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuNovo = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        menuSalvar = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        menuExibir = new javax.swing.JMenu();
        menuOrdem = new javax.swing.JMenuItem();
        menuGrau = new javax.swing.JMenuItem();
        menuGrauRecepcao = new javax.swing.JMenuItem();
        menuGrauEmissao = new javax.swing.JMenuItem();
        menuMatriz = new javax.swing.JMenuItem();
        menuFonte = new javax.swing.JMenuItem();
        menuSumidouro = new javax.swing.JMenuItem();
        menuCaminho = new javax.swing.JMenuItem();
        menuCadeia = new javax.swing.JMenuItem();
        menuIncidentes = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenuItem();
        menuAdjacente = new javax.swing.JMenuItem();
        menuConjunto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuKruskal = new javax.swing.JMenuItem();
        menuPrim = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuGrafico = new javax.swing.JMenu();
        menuNome = new javax.swing.JMenuItem();
        menuPeso = new javax.swing.JMenuItem();
        menuAjustar = new javax.swing.JMenuItem();
        menuNormalizar = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        setForeground(new java.awt.Color(102, 255, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(226, 226, 226));

        iconNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/novo.png"))); // NOI18N
        iconNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconNovoMouseClicked(evt);
            }
        });

        iconAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/abrir.png"))); // NOI18N
        iconAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAbrirMouseClicked(evt);
            }
        });

        iconSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salvarComo.png"))); // NOI18N
        iconSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconSalvarMouseClicked(evt);
            }
        });

        btnMatrizAdj.setBackground(new java.awt.Color(255, 255, 255));
        btnMatrizAdj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnMatrizAdj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ma.png"))); // NOI18N
        btnMatrizAdj.setText("Matriz Adj");
        btnMatrizAdj.setBorder(null);
        btnMatrizAdj.setContentAreaFilled(false);
        btnMatrizAdj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatrizAdj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizAdjActionPerformed(evt);
            }
        });

        btnMatrizInc.setBackground(new java.awt.Color(255, 255, 255));
        btnMatrizInc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnMatrizInc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mi.png"))); // NOI18N
        btnMatrizInc.setText("Matriz Inc");
        btnMatrizInc.setBorder(null);
        btnMatrizInc.setContentAreaFilled(false);
        btnMatrizInc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatrizInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizIncActionPerformed(evt);
            }
        });

        btnListaAdj.setBackground(new java.awt.Color(255, 255, 255));
        btnListaAdj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnListaAdj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/la.png"))); // NOI18N
        btnListaAdj.setText("Lista Adj");
        btnListaAdj.setBorder(null);
        btnListaAdj.setContentAreaFilled(false);
        btnListaAdj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListaAdj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaAdjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconSalvar)
                .addGap(22, 22, 22)
                .addComponent(btnMatrizAdj, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMatrizInc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListaAdj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnListaAdj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMatrizInc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMatrizAdj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(iconSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        display.setEditable(false);
        display.setBackground(new java.awt.Color(233, 233, 233));
        display.setColumns(20);
        display.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        display.setRows(5);
        display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(display);

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAdicionarVertice.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarVertice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdicionarVertice.setText("Adicionar");
        btnAdicionarVertice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdicionarVertice.setContentAreaFilled(false);
        btnAdicionarVertice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarVertice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionarVerticeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdicionarVerticeMouseExited(evt);
            }
        });
        btnAdicionarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarVerticeActionPerformed(evt);
            }
        });

        txtaddVertice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtaddVertice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Nome");

        btnAlterarVertice.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterarVertice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAlterarVertice.setText("Alterar");
        btnAlterarVertice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAlterarVertice.setContentAreaFilled(false);
        btnAlterarVertice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarVertice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarVerticeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarVerticeMouseExited(evt);
            }
        });
        btnAlterarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarVerticeActionPerformed(evt);
            }
        });

        btnDeletarVertice.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletarVertice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDeletarVertice.setText("Deletar");
        btnDeletarVertice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeletarVertice.setContentAreaFilled(false);
        btnDeletarVertice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletarVertice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeletarVerticeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeletarVerticeMouseExited(evt);
            }
        });
        btnDeletarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarVerticeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtaddVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionarVertice, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(txtaddVertice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlterarVertice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeletarVertice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Vertice");

        jLabel6.setBackground(new java.awt.Color(102, 255, 102));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Aresta");

        jPanel6.setBackground(new java.awt.Color(229, 229, 229));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAdicionarAresta.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarAresta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdicionarAresta.setText("Adicionar");
        btnAdicionarAresta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdicionarAresta.setContentAreaFilled(false);
        btnAdicionarAresta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarAresta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionarArestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdicionarArestaMouseExited(evt);
            }
        });
        btnAdicionarAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarArestaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Origem");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Destino");

        txtNomeAresta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNomeAresta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Nome");

        btndeletarAresta.setBackground(new java.awt.Color(255, 255, 255));
        btndeletarAresta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btndeletarAresta.setText("Deletar");
        btndeletarAresta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btndeletarAresta.setContentAreaFilled(false);
        btndeletarAresta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndeletarAresta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeletarArestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeletarArestaMouseExited(evt);
            }
        });
        btndeletarAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarArestaActionPerformed(evt);
            }
        });

        btnAlterarAresta.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterarAresta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAlterarAresta.setText("Alterar");
        btnAlterarAresta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAlterarAresta.setContentAreaFilled(false);
        btnAlterarAresta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarAresta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarArestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarArestaMouseExited(evt);
            }
        });
        btnAlterarAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarArestaActionPerformed(evt);
            }
        });

        txtPesoAresta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPesoAresta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Peso");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtNomeAresta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesoAresta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAdicionarAresta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndeletarAresta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarAresta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDestino)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cbOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeAresta)
                            .addComponent(txtPesoAresta))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdicionarAresta, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btndeletarAresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterarAresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Nome:");

        lblNomeGrafo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNomeGrafo.setText("none");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Tipo:");

        lblTipoGrafo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTipoGrafo.setText("none");

        btnLimpaVA.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpaVA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLimpaVA.setText("Limpar V/A");
        btnLimpaVA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLimpaVA.setContentAreaFilled(false);
        btnLimpaVA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpaVA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpaVAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpaVAMouseExited(evt);
            }
        });
        btnLimpaVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaVAActionPerformed(evt);
            }
        });

        btnLimpaAresta.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpaAresta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLimpaAresta.setText("Limpar arestas");
        btnLimpaAresta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLimpaAresta.setContentAreaFilled(false);
        btnLimpaAresta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpaAresta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpaArestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpaArestaMouseExited(evt);
            }
        });
        btnLimpaAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaArestaActionPerformed(evt);
            }
        });

        btnMostrarVA.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarVA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMostrarVA.setText("Mostrar V/A");
        btnMostrarVA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMostrarVA.setContentAreaFilled(false);
        btnMostrarVA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarVA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarVAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarVAMouseExited(evt);
            }
        });
        btnMostrarVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVAActionPerformed(evt);
            }
        });

        btnGerarGrafico.setBackground(new java.awt.Color(255, 255, 255));
        btnGerarGrafico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGerarGrafico.setText("Gerar grafico");
        btnGerarGrafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGerarGrafico.setContentAreaFilled(false);
        btnGerarGrafico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerarGrafico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGerarGraficoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGerarGraficoMouseExited(evt);
            }
        });
        btnGerarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarGraficoActionPerformed(evt);
            }
        });

        lblGrafico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblGrafico.setText("Grafico");

        imgGrafico.setBackground(new java.awt.Color(255, 255, 255));
        imgGrafico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        imgGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/os/img/fileB.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel3)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnLimpaVA, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimpaAresta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMostrarVA, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGerarGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNomeGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipoGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGrafico)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(imgGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpaVA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpaAresta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostrarVA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGerarGrafico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuArquivo.setText("Arquivo");

        menuNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/novo.png"))); // NOI18N
        menuNovo.setText("Novo");
        menuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoActionPerformed(evt);
            }
        });
        menuArquivo.add(menuNovo);

        menuAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/abrir.png"))); // NOI18N
        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        menuArquivo.add(menuAbrir);

        menuSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salvarComo.png"))); // NOI18N
        menuSalvar.setText("Salvar como...");
        menuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSalvar);

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSair);

        jMenuBar1.add(menuArquivo);

        menuExibir.setText("Exibir");

        menuOrdem.setText("Ordem");
        menuOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOrdemActionPerformed(evt);
            }
        });
        menuExibir.add(menuOrdem);

        menuGrau.setText("Grau");
        menuGrau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGrauActionPerformed(evt);
            }
        });
        menuExibir.add(menuGrau);

        menuGrauRecepcao.setText("Grau de recepção");
        menuGrauRecepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGrauRecepcaoActionPerformed(evt);
            }
        });
        menuExibir.add(menuGrauRecepcao);

        menuGrauEmissao.setText("Grau de emissão");
        menuGrauEmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGrauEmissaoActionPerformed(evt);
            }
        });
        menuExibir.add(menuGrauEmissao);

        menuMatriz.setText("Matrizes");
        menuMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMatrizActionPerformed(evt);
            }
        });
        menuExibir.add(menuMatriz);

        menuFonte.setText("Fonte");
        menuFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFonteActionPerformed(evt);
            }
        });
        menuExibir.add(menuFonte);

        menuSumidouro.setText("Sumidouro");
        menuSumidouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSumidouroActionPerformed(evt);
            }
        });
        menuExibir.add(menuSumidouro);

        menuCaminho.setText("Caminho");
        menuCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaminhoActionPerformed(evt);
            }
        });
        menuExibir.add(menuCaminho);

        menuCadeia.setText("Cadeia");
        menuCadeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadeiaActionPerformed(evt);
            }
        });
        menuExibir.add(menuCadeia);

        menuIncidentes.setText("Incidentes");
        menuIncidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIncidentesActionPerformed(evt);
            }
        });
        menuExibir.add(menuIncidentes);

        menuInfo.setText("Tipo");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });
        menuExibir.add(menuInfo);

        menuAdjacente.setText("Adjacentes");
        menuAdjacente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdjacenteActionPerformed(evt);
            }
        });
        menuExibir.add(menuAdjacente);

        menuConjunto.setText("Conjunto");
        menuConjunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConjuntoActionPerformed(evt);
            }
        });
        menuExibir.add(menuConjunto);

        jMenuBar1.add(menuExibir);

        jMenu3.setText("Algoritimos");

        menuKruskal.setText("Kruskal");
        menuKruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKruskalActionPerformed(evt);
            }
        });
        jMenu3.add(menuKruskal);

        menuPrim.setText("Prim");
        menuPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrimActionPerformed(evt);
            }
        });
        jMenu3.add(menuPrim);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Ferramentas");

        menuGrafico.setText("Grafico");

        menuNome.setText("Mostrar nome");
        menuNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNomeActionPerformed(evt);
            }
        });
        menuGrafico.add(menuNome);

        menuPeso.setText("Mostrar peso");
        menuPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesoActionPerformed(evt);
            }
        });
        menuGrafico.add(menuPeso);

        menuAjustar.setText("Ajustar");
        menuAjustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjustarActionPerformed(evt);
            }
        });
        menuGrafico.add(menuAjustar);

        menuNormalizar.setText("Normalizar");
        menuNormalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNormalizarActionPerformed(evt);
            }
        });
        menuGrafico.add(menuNormalizar);

        jMenu1.add(menuGrafico);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        abrirArquivo();
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarActionPerformed
        salvarArquivo();
    }//GEN-LAST:event_menuSalvarActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed
        if (graph.completo() == true) {
            display.setText("Grafo Completo");
        } else if (graph.regular() == true) {
            display.setText("Grafo Regular");
        } else if (graph.multigrafo() == true) {
            display.setText("Multigrafo");
        }
    }//GEN-LAST:event_menuInfoActionPerformed

    private void menuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoActionPerformed
        novoArquivo();
    }//GEN-LAST:event_menuNovoActionPerformed

    private void menuMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatrizActionPerformed
        display.setText("\t==========Matriz Adjacência==========\n\n" + graph.matrizAdjacencia() + "\n\n\n"
                + "\t==========Matriz Incidência==========\n\n" + graph.matrizIncidencia(graph) + "\n\n\n"
                + "\t==========Lista Adjacência==========\n\n" + graph.listaAdjacencia(graph));
    }//GEN-LAST:event_menuMatrizActionPerformed

    private void menuIncidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIncidentesActionPerformed
        display.setText("\t==========Incidentes==========\n\n" + graph.getIncidentes());
    }//GEN-LAST:event_menuIncidentesActionPerformed

    private void menuAdjacenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdjacenteActionPerformed
        display.setText("\t==========Adjacentes==========\n\n" + graph.getAdjacentes());
    }//GEN-LAST:event_menuAdjacenteActionPerformed

    private void menuConjuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConjuntoActionPerformed
        display.setText("\t==========Conjunto==========\n\n" + graph.conjunto(graph));
    }//GEN-LAST:event_menuConjuntoActionPerformed

    private void menuPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesoActionPerformed
        m = 99;
        gerarGraph();
    }//GEN-LAST:event_menuPesoActionPerformed

    private void menuNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNomeActionPerformed
        m = 0;
        gerarGraph();
    }//GEN-LAST:event_menuNomeActionPerformed

    private void menuAjustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjustarActionPerformed
        if (graph.getEdges().isEmpty()) {
            imgGrafico.setSize(300, 80);
        } else {
            imgGrafico.setSize(300, 555);
        }
        gerarGraph();
    }//GEN-LAST:event_menuAjustarActionPerformed

    private void menuNormalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNormalizarActionPerformed
        gerarGraph();
    }//GEN-LAST:event_menuNormalizarActionPerformed

    private void menuGrauRecepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGrauRecepcaoActionPerformed
        if (graph.getEdgedefault().equals("directed")) {
            display.setText(graph.grauRecepcao());
        } else {
            display.setText("Não se aplica em grafo  não orientado");
        }
    }//GEN-LAST:event_menuGrauRecepcaoActionPerformed

    private void menuGrauEmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGrauEmissaoActionPerformed
        if (graph.getEdgedefault().equals("directed")) {
            display.setText(graph.grauEmissao());
        } else {
            display.setText("Não se aplica em grafo  não orientado");
        }
    }//GEN-LAST:event_menuGrauEmissaoActionPerformed

    private void menuFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFonteActionPerformed
        if (graph.getEdgedefault().equals("directed")) {
            display.setText(graph.fonte());
        } else {
            display.setText("Não se aplica em grafo  não orientado");
        }
    }//GEN-LAST:event_menuFonteActionPerformed

    private void menuSumidouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSumidouroActionPerformed
        if (graph.getEdgedefault().equals("directed")) {
            display.setText(graph.sumidouro());
        } else {
            display.setText("Não se aplica em grafo  não orientado");
        }
    }//GEN-LAST:event_menuSumidouroActionPerformed

    private void menuOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOrdemActionPerformed
        display.setText("\t========== Ordem ==========\n\nOrdem do Grafo é: " + graph.getNodes().size());
    }//GEN-LAST:event_menuOrdemActionPerformed

    private void menuGrauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGrauActionPerformed
        display.setText("\t========== Grau ==========\n" + graph.getGrau());
    }//GEN-LAST:event_menuGrauActionPerformed

    private void btnAlterarArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarArestaActionPerformed
        if (ede == null) {
            ede = new frmEditarAresta();
            ede.setVisible(true);

            ede.setAlteracao(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault());
        } else {
            ede.setVisible(true);
            ede.setState(frmEditarAresta.NORMAL);
            ede.setAlteracao(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault());
        }
    }//GEN-LAST:event_btnAlterarArestaActionPerformed

    private void btnAlterarArestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarArestaMouseExited
        btnAlterarAresta.setContentAreaFilled(false);
    }//GEN-LAST:event_btnAlterarArestaMouseExited

    private void btnAlterarArestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarArestaMouseEntered
        btnAlterarAresta.setContentAreaFilled(true);
        btnAlterarAresta.setBackground(Color.gray);
    }//GEN-LAST:event_btnAlterarArestaMouseEntered

    private void btndeletarArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarArestaActionPerformed
        display.setText("\t==========Aresta==========\n\n" + graph.removerEdge((String) cbOrigem.getSelectedItem(),
                (String) cbDestino.getSelectedItem()));
    }//GEN-LAST:event_btndeletarArestaActionPerformed

    private void btndeletarArestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeletarArestaMouseExited
        btndeletarAresta.setContentAreaFilled(false);
    }//GEN-LAST:event_btndeletarArestaMouseExited

    private void btndeletarArestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeletarArestaMouseEntered
        btndeletarAresta.setContentAreaFilled(true);
        btndeletarAresta.setBackground(Color.gray);
    }//GEN-LAST:event_btndeletarArestaMouseEntered

    private void btnAdicionarArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarArestaActionPerformed
        if (txtNomeAresta.getText().isEmpty()) {//verifica se é vazio
            display.setText("Nome invalido");
        } else {
            if (txtPesoAresta.getText().isEmpty()) {
                if (graph.addEdges((String) cbOrigem.getSelectedItem(), (String) cbDestino.getSelectedItem(), 0, txtNomeAresta.getText()).equals("erro")) {
                    display.setText("Existe uma aresta com esse nome!");
                } else {
                    ImprimeEdge();
                }
            } else if (graph.addEdges((String) cbOrigem.getSelectedItem(), (String) cbDestino.getSelectedItem(), Float.parseFloat(txtPesoAresta.getText()), txtNomeAresta.getText()).equals("erro")) {
                display.setText("Existe uma aresta com esse nome!");
            } else {
                ImprimeEdge();
            }
        }
        txtNomeAresta.setText("");
        txtPesoAresta.setText("");
    }//GEN-LAST:event_btnAdicionarArestaActionPerformed

    private void btnAdicionarArestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarArestaMouseExited
        btnAdicionarAresta.setContentAreaFilled(false);
    }//GEN-LAST:event_btnAdicionarArestaMouseExited

    private void btnAdicionarArestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarArestaMouseEntered
        btnAdicionarAresta.setContentAreaFilled(true);
        btnAdicionarAresta.setBackground(Color.gray);
    }//GEN-LAST:event_btnAdicionarArestaMouseEntered

    private void btnDeletarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarVerticeActionPerformed
        if (graph.removerNode(txtaddVertice.getText()) == true) {
            if (!graph.getNodes().isEmpty()) {
                display.setText(graph.ImprimeNode());
                gerarGraph();
            } else {
                String path = "src\\os\\img\\fileB.png";
                BufferedImage img = null;
                try {
                    img = ImageIO.read(new File(path));
                } catch (IOException ex) {
                    Logger.getLogger(frmInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
                ImageIcon image = new ImageIcon(ImageScale(img, imgGrafico.getWidth(), imgGrafico.getHeight()));
                imgGrafico.setIcon(image);
                display.setText("Lista: vazia");
            }
        } else {
            display.setForeground(Color.red);
            display.setText("Erro! não foi possivel remover\n\nCausas\n1ª - vertice inexistente\n2ª - Parametro vazio");
        }
        cbOrigem.removeItem(txtaddVertice.getText());
        cbDestino.removeItem(txtaddVertice.getText());
        txtaddVertice.setText("");
    }//GEN-LAST:event_btnDeletarVerticeActionPerformed

    private void btnDeletarVerticeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarVerticeMouseExited
        btnDeletarVertice.setContentAreaFilled(false);
    }//GEN-LAST:event_btnDeletarVerticeMouseExited

    private void btnDeletarVerticeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarVerticeMouseEntered
        btnDeletarVertice.setContentAreaFilled(true);
        btnDeletarVertice.setBackground(Color.gray);
    }//GEN-LAST:event_btnDeletarVerticeMouseEntered

    private void btnAlterarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVerticeActionPerformed
        if (edn == null) {
            edn = new frmEditarNode();
            edn.setVisible(true);

            edn.setAlteracao(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault());
        } else {
            edn.setVisible(true);
            edn.setState(frmEditarNode.NORMAL);
            edn.setAlteracao(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault());
        }
        //        cbOrigem.removeAllItems();
        //        cbDestino.removeAllItems();

        //        graph.getNodes().clear();
        //        graph.getEdges().clear();
    }//GEN-LAST:event_btnAlterarVerticeActionPerformed

    private void btnAlterarVerticeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarVerticeMouseExited
        btnAlterarVertice.setContentAreaFilled(false);
    }//GEN-LAST:event_btnAlterarVerticeMouseExited

    private void btnAlterarVerticeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarVerticeMouseEntered
        btnAlterarVertice.setContentAreaFilled(true);
        btnAlterarVertice.setBackground(Color.gray);
    }//GEN-LAST:event_btnAlterarVerticeMouseEntered

    private void btnAdicionarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarVerticeActionPerformed
        if (txtaddVertice.getText().isEmpty()) {
            display.setForeground(Color.red);
            display.setText("Campo vertice está vazio!\nColoqueum nome valido");
        } else {
            if (graph.addNodes(txtaddVertice.getText()) == true) {
                display.setForeground(Color.red);
                display.setText("Vertice " + txtaddVertice.getText() + " existente!");
            } else {
                display.setForeground(Color.black);
                display.setText(graph.ImprimeNode());
                cbOrigem.addItem(txtaddVertice.getText());
                cbDestino.addItem(txtaddVertice.getText());
            }
        }
        txtaddVertice.setText("");
    }//GEN-LAST:event_btnAdicionarVerticeActionPerformed

    private void btnAdicionarVerticeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarVerticeMouseExited
        btnAdicionarVertice.setContentAreaFilled(false);
    }//GEN-LAST:event_btnAdicionarVerticeMouseExited

    private void btnAdicionarVerticeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarVerticeMouseEntered
        btnAdicionarVertice.setContentAreaFilled(true);
        btnAdicionarVertice.setBackground(Color.gray);
    }//GEN-LAST:event_btnAdicionarVerticeMouseEntered

    private void btnListaAdjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaAdjActionPerformed
        display.setText("\t==========Lista Adjacência==========\n\n" + graph.listaAdjacencia(graph));
    }//GEN-LAST:event_btnListaAdjActionPerformed

    private void btnMatrizIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizIncActionPerformed
        display.setText("\t==========Matriz Incidência==========\n\n" + graph.matrizIncidencia(graph));
    }//GEN-LAST:event_btnMatrizIncActionPerformed

    private void btnMatrizAdjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizAdjActionPerformed
        display.setText("\t==========Matriz Adjacência==========\n\n" + graph.matrizAdjacencia());
    }//GEN-LAST:event_btnMatrizAdjActionPerformed

    private void iconSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconSalvarMouseClicked
        salvarArquivo();
    }//GEN-LAST:event_iconSalvarMouseClicked

    private void iconAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAbrirMouseClicked
        abrirArquivo();
    }//GEN-LAST:event_iconAbrirMouseClicked

    private void iconNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconNovoMouseClicked
        novoArquivo();
    }//GEN-LAST:event_iconNovoMouseClicked

    private void btnGerarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarGraficoActionPerformed
        gerarGraph();
    }//GEN-LAST:event_btnGerarGraficoActionPerformed

    private void btnGerarGraficoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarGraficoMouseExited
        btnGerarGrafico.setContentAreaFilled(false);
    }//GEN-LAST:event_btnGerarGraficoMouseExited

    private void btnGerarGraficoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarGraficoMouseEntered
        btnGerarGrafico.setContentAreaFilled(true);
        btnGerarGrafico.setBackground(Color.gray);
    }//GEN-LAST:event_btnGerarGraficoMouseEntered

    private void btnMostrarVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVAActionPerformed
        display.setText(graph.imprimeListas());
    }//GEN-LAST:event_btnMostrarVAActionPerformed

    private void btnMostrarVAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVAMouseExited
        btnMostrarVA.setContentAreaFilled(false);
    }//GEN-LAST:event_btnMostrarVAMouseExited

    private void btnMostrarVAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVAMouseEntered
        btnMostrarVA.setContentAreaFilled(true);
        btnMostrarVA.setBackground(Color.gray);
    }//GEN-LAST:event_btnMostrarVAMouseEntered

    private void btnLimpaArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaArestaActionPerformed
        graph.getEdges().clear();
        display.setText(graph.imprimeListas());
    }//GEN-LAST:event_btnLimpaArestaActionPerformed

    private void btnLimpaArestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpaArestaMouseExited
        btnLimpaAresta.setContentAreaFilled(false);
    }//GEN-LAST:event_btnLimpaArestaMouseExited

    private void btnLimpaArestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpaArestaMouseEntered
        btnLimpaAresta.setContentAreaFilled(true);
        btnLimpaAresta.setBackground(Color.gray);
    }//GEN-LAST:event_btnLimpaArestaMouseEntered

    private void btnLimpaVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaVAActionPerformed
        cbOrigem.removeAllItems();
        cbDestino.removeAllItems();
        graph.getNodes().clear();
        graph.getEdges().clear();
    }//GEN-LAST:event_btnLimpaVAActionPerformed

    private void btnLimpaVAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpaVAMouseExited
        btnLimpaVA.setContentAreaFilled(false);
    }//GEN-LAST:event_btnLimpaVAMouseExited

    private void btnLimpaVAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpaVAMouseEntered
        btnLimpaVA.setContentAreaFilled(true);
        btnLimpaVA.setBackground(Color.gray);
    }//GEN-LAST:event_btnLimpaVAMouseEntered

    private void menuCadeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadeiaActionPerformed
        if (graph.getEdgedefault().equals("undirected")) {
            if (vcad == null) {
                vcad = new frmCadeia();
                vcad.setVisible(true);
                vcad.setAlteracao(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault());
            } else {
                vcad.setVisible(true);
                vcad.setState(frmCadeia.NORMAL);
                vcad.setAlteracao(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault());
            }
        }
    }//GEN-LAST:event_menuCadeiaActionPerformed

    private void menuCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaminhoActionPerformed
        if (graph.getEdgedefault().equals("directed")) {
            if (vcam == null) {
                vcam = new frmCaminho();
                vcam.setVisible(true);
                vcam.setAlteracao(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault());
            } else {
                vcam.setVisible(true);
                vcam.setState(frmCadeia.NORMAL);
                vcam.setAlteracao(graph.getNodes(), graph.getEdges(), graph.getId(), graph.getEdgedefault());
            }
        }
    }//GEN-LAST:event_menuCaminhoActionPerformed

    private void menuKruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKruskalActionPerformed
        String r = "";
        List<Node> lista = new ArrayList<Node>();
        lista = graph.Kruskal();

        if (lista.isEmpty()) {
            display.setText("erro");
        } else {
            for (int i = 0; i < lista.size(); i++) {
                r += "{ " + lista.get(i).getId() + "}";
            }
            display.setText(r);
        }
        graph.setNodes(lista);
        recuperaLista(1);
    }//GEN-LAST:event_menuKruskalActionPerformed

    private void menuPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrimActionPerformed
        String r = "";
        List<Node> lista = new ArrayList<Node>();
        lista = graph.Prim();

        if (lista.isEmpty()) {
            display.setText("erro");
        } else {
            for (int i = 0; i < lista.size(); i++) {
                r += "{ " + lista.get(i).getId() + "}";
            }
            display.setText(r);
        }
        graph.setNodes(lista);
        recuperaLista(1);
    }//GEN-LAST:event_menuPrimActionPerformed
    public void recuperaLista(int n) { // para n perder a lista original
        if (n == 1) {
            graph.getEdges().clear();
            for (int i = 0; i < listaRec.size(); i++) { //Adiciona os vertices no combobox    
                graph.addEdge(listaRec.get(i));
            }

        } else {
            for (int i = 0; i < graph.getEdges().size(); i++) { //Adiciona os vertices no combobox    
                listaRec.add(graph.getEdges().get(i));
            }
        }
    }

    public void getAlteracao(List<Node> node, List<Edge> edge, String nome, String tipo) {
        graph.setId(nome);
        graph.setEdgedefault(tipo);
        graph.setNodes(node);
        graph.setEdges(edge);

        lblNomeGrafo.setText(graph.getId());
        lblTipoGrafo.setText(graph.getEdgedefault());
        if (tipo.equals("directed")) {
            m = 1;
        } else {
            m = 0;
        }
        for (int i = 0; i < graph.getNodes().size(); i++) { //Adiciona os vertices no combobox    
            cbOrigem.addItem(graph.getNodes().get(i).getId());
            cbDestino.addItem(graph.getNodes().get(i).getId());
        }
        display.setText(graph.imprimeListas());
    }

    public void getCadeiaOuCaminho(List<Node> node, List<Edge> edge, String nome, String tipo, String r) {
        graph.setId(nome);
        graph.setEdgedefault(tipo);
        graph.setNodes(node);
        graph.setEdges(edge);

        lblNomeGrafo.setText(graph.getId());
        lblTipoGrafo.setText(graph.getEdgedefault());
        if (tipo.equals("directed")) {
            m = 1;
        } else {
            m = 0;
        }
        for (int i = 0; i < graph.getNodes().size(); i++) { //Adiciona os vertices no combobox    
            cbOrigem.addItem(graph.getNodes().get(i).getId());
            cbDestino.addItem(graph.getNodes().get(i).getId());
        }
        display.setText(r);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);  //Fecha o jframe sem fechar tudo

    }

    public void novoArquivo() {
        frmCriarGrafo fcg = new frmCriarGrafo();
        fcg.setVisible(true);
    }

    public void ImprimeEdge() {
        String r = "\t========== Aresta ==========\n\n Id\tOrigem\tDestino\tPeso\n";

        for (int i = 0; i < graph.getEdges().size(); i++) {
            r += " " + graph.getEdges().get(i).getId() + "\t" + graph.getEdges().get(i).getNode1().getId() + "\t" + graph.getEdges().get(i).getNode2().getId() + "\t" + graph.getEdges().get(i).getPeso() + "\n";
        }
        display.setText(r);
    }

    public void setNomeGrafo(String nome) {
        display.setText(nome);
        graph.setId(nome);
    }

    //Recebe os dados da tela frmCriarGrafo
    public void setAbrirGrafo(List<Node> node, List<Edge> edge, String nome, String tipo) {
        graph.setNodes(node);
        graph.setEdges(edge);
        graph.setId(nome);
        graph.setEdgedefault(tipo);

        recuperaLista(0);

        if (tipo.equals("undirected")) {
            menuGrauEmissao.setEnabled(false);
            menuGrauRecepcao.setEnabled(false);
            menuFonte.setEnabled(false);
            menuSumidouro.setEnabled(false);
            menuCaminho.setEnabled(false);
            menuCadeia.setEnabled(true);
            m = 0;
        } else {
            menuGrauEmissao.setEnabled(true);
            menuGrauRecepcao.setEnabled(true);
            menuFonte.setEnabled(true);
            menuSumidouro.setEnabled(true);
            menuCaminho.setEnabled(true);
            menuCadeia.setEnabled(false);
            m = 1;
        }
        for (int i = 0; i < graph.getNodes().size(); i++) { //Adiciona os vertices no combobox    
            cbOrigem.addItem(graph.getNodes().get(i).getId());
            cbDestino.addItem(graph.getNodes().get(i).getId());
        }
        lblNomeGrafo.setText(graph.getId());
        lblTipoGrafo.setText(graph.getEdgedefault());
        display.setText(graph.imprimeListas());

        JOptionPane.showMessageDialog(null, "Arquivo carregado com sucesso...");
    }

    public void salvarArquivo() {
        graph.getGrau();
        graphml.getGraph();

        JFileChooser arquivo = new JFileChooser();
        FileNameExtensionFilter filtroXML = new FileNameExtensionFilter("Arquivos XML", "xml");
        arquivo.addChoosableFileFilter(filtroXML);
        arquivo.setAcceptAllFileFilterUsed(false);

        if (arquivo.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            display.setText(arquivo.getSelectedFile().getAbsolutePath());
            choose = display.getText();
        }

        XStream xstream = new XStream(new DomDriver());
        String xml = null;

        xstream.omitField(Edge.class, "node1");
        xstream.omitField(Edge.class, "node2");
        xstream.alias("graphml", Graphml.class);
        xstream.alias("graph", Graph.class);
        xstream.alias("node", Node.class);
        xstream.alias("edge", Edge.class);
        xstream.useAttributeFor("id", String.class);
        xstream.useAttributeFor("edgedefault", String.class);
        xstream.useAttributeFor("source", String.class);
        xstream.useAttributeFor("target", String.class);
        xstream.useAttributeFor("xmlns", String.class);
        xstream.useAttributeFor("degree", int.class);
        xstream.useAttributeFor("weight", float.class);
        xstream.addImplicitArray(Graph.class, "nodes");
        xstream.addImplicitArray(Graph.class, "edges");
        graphml.setGraph(graph);

        try {
            xml = xstream.toXML(graphml);
            System.out.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" + xml);
            File file = new File(choose + ".xml");
            PrintWriter print = new PrintWriter(file);
            print.write(xml);
            print.flush();
            print.close();
            display.setText(xml);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void abrirArquivo() {
        cbOrigem.removeAllItems();
        cbDestino.removeAllItems();

        JFileChooser arquivo = new JFileChooser();
        FileNameExtensionFilter filtroXML = new FileNameExtensionFilter("Arquivos XML", "xml");
        arquivo.addChoosableFileFilter(filtroXML);
        arquivo.setAcceptAllFileFilterUsed(false);
        if (arquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            display.setText(arquivo.getSelectedFile().getAbsolutePath());
            choose = display.getText();
            try {
                FileReader leitor = new FileReader(choose);
                XStream xstream = new XStream(new DomDriver());

                xstream.omitField(Edge.class, "node1");
                xstream.omitField(Edge.class, "node2");
                xstream.alias("graphml", Graphml.class);
                xstream.alias("graph", Graph.class);
                xstream.alias("node", Node.class);
                xstream.alias("edge", Edge.class);
                xstream.useAttributeFor("id", String.class);
                xstream.useAttributeFor("edgedefault", String.class);
                xstream.useAttributeFor("source", String.class);
                xstream.useAttributeFor("target", String.class);
                xstream.useAttributeFor("xmlns", String.class);
                xstream.useAttributeFor("id", String.class);
                xstream.useAttributeFor("degree", int.class);
                xstream.useAttributeFor("weight", float.class);
                xstream.addImplicitArray(Graph.class, "nodes");
                xstream.addImplicitArray(Graph.class, "edges");

                graphml = null;
                graphml = (Graphml) xstream.fromXML(leitor);
                ArrayList lst = (ArrayList) graphml.getGraph().getEdges();
                graphml.getGraph().setNodes(new ArrayList<Node>());
                graphml.getGraph().setEdges(new ArrayList<Edge>());

                for (Object e : lst) {
                    if (e instanceof Node) {
                        graphml.getGraph().getNodes().add((Node) e);
                    } else {
                        graphml.getGraph().getEdges().add((Edge) e);
                    }
                }

                for (Edge edge : graphml.getGraph().getEdges()) {
                    for (Node no : graphml.getGraph().getNodes()) {
                        if (no.getId().equals(edge.getSoucer())) {
                            edge.setNode1(no);
                        }
                        if (no.getId().equals(edge.getTarget())) {
                            edge.setNode2(no);
                        }
                    }
                }
                listaNode = (ArrayList<Node>) graphml.getGraph().getNodes();
                listaEdge = (ArrayList<Edge>) graphml.getGraph().getEdges();

                graph.setNodes(listaNode);
                graph.setEdges(listaEdge);

                String r = "", r2 = "";
                for (int i = 0; i < graph.getNodes().size(); i++) {
                    cbOrigem.addItem(graph.getNodes().get(i).getId());
                    cbDestino.addItem(graph.getNodes().get(i).getId());
                }
                graph.setId(graphml.getGraph().getId());
                graph.setEdgedefault(graphml.getGraph().getEdgedefault());
                lblNomeGrafo.setText(graph.getId());
                lblTipoGrafo.setText(graph.getEdgedefault());

                if (graph.getEdgedefault().equals("directed")) {
                    graph.setEdgedefault("directed");
                    menuGrauEmissao.setEnabled(true);
                    menuGrauRecepcao.setEnabled(true);
                    menuFonte.setEnabled(true);
                    menuSumidouro.setEnabled(true);
                    menuCaminho.setEnabled(true);
                    menuCadeia.setEnabled(false);
                    m = 1;
                } else {
                    graph.setEdgedefault("undirected");
                    menuGrauEmissao.setEnabled(false);
                    menuGrauRecepcao.setEnabled(false);
                    menuFonte.setEnabled(false);
                    menuSumidouro.setEnabled(false);
                    menuCaminho.setEnabled(false);
                    m = 0;
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(frmInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void setNovoGrafo(String nome, String qt, String tipo) {
        if (tipo.equals("directed")) {
            graph.setEdgedefault("directed");
            menuGrauEmissao.setEnabled(true);
            menuGrauRecepcao.setEnabled(true);
            menuFonte.setEnabled(true);
            menuSumidouro.setEnabled(true);
            menuCaminho.setEnabled(true);
            menuCadeia.setEnabled(false);
            m = 1;
        } else {
            graph.setEdgedefault("undirected");
            menuGrauEmissao.setEnabled(false);
            menuGrauRecepcao.setEnabled(false);
            menuFonte.setEnabled(false);
            menuSumidouro.setEnabled(false);
            menuCaminho.setEnabled(false);
            m = 0;
        }
        graph.setId(nome);

        for (int i = 0; i < Integer.parseInt(qt); i++) {
            Node node = new Node();
            node.setId(Integer.toString(i + 1));
            graph.addNode(node);
            cbOrigem.addItem(Integer.toString(i + 1));
            cbDestino.addItem(Integer.toString(i + 1));
        }
        lblNomeGrafo.setText(graph.getId());
        lblTipoGrafo.setText(graph.getEdgedefault());
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);  //Fecha o jframe sem fechar tudo
    }

    public Image ImageScale(Image img, int w, int h) {
        BufferedImage image = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h, this);
        g2.dispose();
        return image;

    }

    public void gerarGraph() {

//////        graph.setEdgedefault(graph.getEdgedefault());
//////        graph.setNodes(graph.getNodes());
//////        graph.setEdges(graph.getEdges());
        display.setText(graph.geraGraph(m));

        for (int i = 0; i < graph.getNodes().size(); i++) { 
            //laço pegando a lista de nos
            try {
                Process p;
                File arquivo = new File("src\\os\\dot\\fileS.dot");
                try (FileWriter fw = new FileWriter(arquivo)) {

                    fw.write("" + graph.geraGraph(m));

                    fw.flush();
                } catch (IOException ex) {
                    System.out.println("Erro ao Criar Arquivo: " + ex.getMessage());
                }

                String commandLine = "dot -Tpng " + arquivo.getCanonicalPath() + " -o src\\os\\img\\fileS.png";

                p = Runtime.getRuntime().exec(commandLine);
                while (p.isAlive()) {
                }

                String path = "src\\os\\img\\fileS.png";
                BufferedImage img = ImageIO.read(new File(path));
                ImageIcon image = new ImageIcon(ImageScale(img, imgGrafico.getWidth(), imgGrafico.getHeight()));
                imgGrafico.setIcon(image);
                imgGrafico.setText("");

            } catch (IOException ex) {
                System.out.println("Erro do Executar Comando: " + ex.getMessage());
            }
        }
    }

    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 4, (ds.height - dw.height) / 30);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAresta;
    private javax.swing.JButton btnAdicionarVertice;
    private javax.swing.JButton btnAlterarAresta;
    private javax.swing.JButton btnAlterarVertice;
    private javax.swing.JButton btnDeletarVertice;
    private javax.swing.JButton btnGerarGrafico;
    private javax.swing.JButton btnLimpaAresta;
    private javax.swing.JButton btnLimpaVA;
    private javax.swing.JButton btnListaAdj;
    private javax.swing.JButton btnMatrizAdj;
    private javax.swing.JButton btnMatrizInc;
    private javax.swing.JButton btnMostrarVA;
    private javax.swing.JButton btndeletarAresta;
    private javax.swing.JComboBox<String> cbDestino;
    private javax.swing.JComboBox<String> cbOrigem;
    private javax.swing.JTextArea display;
    private javax.swing.JLabel iconAbrir;
    private javax.swing.JLabel iconNovo;
    private javax.swing.JLabel iconSalvar;
    private javax.swing.JLabel imgGrafico;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblGrafico;
    private javax.swing.JLabel lblNomeGrafo;
    private javax.swing.JLabel lblTipoGrafo;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenuItem menuAdjacente;
    private javax.swing.JMenuItem menuAjustar;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuCadeia;
    private javax.swing.JMenuItem menuCaminho;
    private javax.swing.JMenuItem menuConjunto;
    private javax.swing.JMenu menuExibir;
    private javax.swing.JMenuItem menuFonte;
    private javax.swing.JMenu menuGrafico;
    private javax.swing.JMenuItem menuGrau;
    private javax.swing.JMenuItem menuGrauEmissao;
    private javax.swing.JMenuItem menuGrauRecepcao;
    private javax.swing.JMenuItem menuIncidentes;
    private javax.swing.JMenuItem menuInfo;
    private javax.swing.JMenuItem menuKruskal;
    private javax.swing.JMenuItem menuMatriz;
    private javax.swing.JMenuItem menuNome;
    private javax.swing.JMenuItem menuNormalizar;
    private javax.swing.JMenuItem menuNovo;
    private javax.swing.JMenuItem menuOrdem;
    private javax.swing.JMenuItem menuPeso;
    private javax.swing.JMenuItem menuPrim;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSalvar;
    private javax.swing.JMenuItem menuSumidouro;
    private javax.swing.JTextField txtNomeAresta;
    private javax.swing.JTextField txtPesoAresta;
    private javax.swing.JTextField txtaddVertice;
    // End of variables declaration//GEN-END:variables
}
